import { createClient } from '@supabase/supabase-js'
const sb = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_KEY, { auth: { persistSession: false } })
const { count: bloq } = await sb.from('business_customers').select('*',{count:'exact',head:true}).not('blocked_at','is',null)
console.log('Clientes BLOQUEADOS en producción:', bloq)
const { count: manual } = await sb.from('conversation_sessions').select('*',{count:'exact',head:true}).eq('manual_mode', true)
console.log('Sesiones en MODO MANUAL:', manual)
const { count: noleido } = await sb.from('conversation_sessions').select('*',{count:'exact',head:true}).eq('unread_owner', true)
console.log('Sesiones sin leer (alarma):', noleido)
const { count: sesiones } = await sb.from('conversation_sessions').select('*',{count:'exact',head:true})
console.log('Sesiones totales:', sesiones)
const { count: tags } = await sb.from('conversation_tags').select('*',{count:'exact',head:true})
console.log('Etiquetas creadas:', tags)
const { data: perms } = await sb.from('client_users').select('email,role,permissions')
console.log('Usuarios y permisos:'); console.table((perms||[]).map(u=>({email:u.email,role:u.role,perms:JSON.stringify(u.permissions)})))
const { count: silenciados } = await sb.from('business_customers').select('*',{count:'exact',head:true}).not('muted_until','is',null)
console.log('Clientes silenciados por el techo anti-spam:', silenciados)
